### ISSUE TITLE
final_afe_finds.csv 'Name' column missing the last character

### ISSUE THREAD

**Issue by leemordechai** [pyzmark/FLAME_DAI_transformation#1]
See image:
![image](https://github.com/pyzmark/FLAME_DAI_transformation/assets/16713928/95c70e72-f537-4193-81f0-496f076bb0ab)

**Comment by pyzmark** [comment]
Scratch that, we have that information in the afe_fundort spreadsheet. I will just match to that. Much simpler.

**Comment by pyzmark** [comment]
I got the names from afe_fundort and just referenced them to final_afe_finds: they should be pristine. No missing characters, and no garbage at the end of strings.
