### ISSUE TITLE
References in find results

### ISSUE THREAD

**Issue by leemordechai** [pyzmark/FLAME_DAI_transformation#2]
If possible, please add some of the reference to the column. We should keep the link as well, but in general it would be better to have at least the key part of the content on our website without requiring users to click again.

**Comment by pyzmark** [comment]
This will produce garbage-filled values like this "RIC 9, ?BibliographyCRFB 4 (Bremen und Nieders..". This was just one of the problems with dealing with their unstructured data. I suppose I could do it and see how it turned out. I will update you on what this looks like and we can proceed from there.

**Comment by pyzmark** [comment]
Then there is the problem that difference coins have different references, which will mean that big finds will have an endless stream of chaotic RIC/etc references. It will look like this. 

![image](https://github.com/pyzmark/FLAME_DAI_transformation/assets/28210739/94060727-43ca-4501-a56d-8c0def560210)

Let me know what you think.

**Comment by pyzmark** [comment]
I am going to pause this issue until we resolve the above because implementing it would require that I code a method of uniting finds like 3169 that have been rendered as four separate finds, differing only in references.

**Comment by leemordechai** [comment]
What about including links to the coins on the DAI site with a separator (e.g. ||) instead of including the messy concatenation of the references?

**Comment by pyzmark** [comment]
That seems doable. I will play around with it today and get another git upload up.

**Comment by pyzmark** [comment]
This is done, closing.
