### ISSUE TITLE
Certainty in final_afe_finds

### ISSUE THREAD

**Issue by leemordechai** [pyzmark/FLAME_DAI_transformation#3]
Please include a 'certainty' column in the coin find results, and unless there are exceptions, give all entries the value 'highest' (which corresponds to a precision of a few km radius, e.g. a city).

**Comment by pyzmark** [comment]
Ok, I am going to insert '2' as the value, as this is the highest in our datadump, column 'cf_custom_region_vague'. Incidentally, that data dump reveals there are rows that are null values, which should probably be fixed.

**Comment by pyzmark** [comment]
This is done—I have inserted the highest level of certainty for all DAI AFE finds. Please check to make sure I've used the right column name and certainty value. Otherwise, we can close this issue.

**Comment by pyzmark** [comment]
This is in the new commit. Closing. Let me know if we need to reopen.
